import Image from "next/image";
import "../styles/globals.css";
import 'reactflow/dist/style.css';
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Arslan Imtiaz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='body-bg h-screen text-white'>
        {children}
      </body>
    </html>
  );
}
